#!/bin/bash
## script para eliminiar eventos de la base de datos

### elaborado por DIEGO CASTRO octubre 2020
source  ${HOME}/.seiscomp.bash
SERVIDOR=localhost
USER=sysop
PWR=sysop
DATA_BASE=seiscomp
TOP_DIR=/media/HDD/seiscomp/delete

if [[ -z $1 ]]
then
	echo "NO INGRESASTE UN ID"
	exit
else
	EVENT=$1

	if [[ ! -d $TOP_DIR ]]
	then
		mkdir $TOP_DIR
	fi

	cd $TOP_DIR
	rm -f ./delete_event.xml

	scxmldump -fPAMF -E $EVENT -o delete_event.xml \
		-d mysql://${USER}:${PWR}@${SERVIDOR}/${DATA_BASE}

	if [[ -e delete_event.xml ]]
	then
		cp delete_event.xml $TOP_DIR/$EVENT.xml
		scdispatch -i delete_event.xml -O remove
	else
		echo "NO HAY EVENTO"
	fi
fi
