#!/bin/bash

SERVIDOR=localhost
DIR=/tmp/seiscomp/listado
DB=seiscomp
USR=sysop
PSWD=sysop


_main_(){
	if [ ! -d ${DIR} ]
	then
		mkdir -p ${DIR}
	fi

	if [[ ${QUITE} == "1" ]]
	then

		_listado_quite_ "${H}" "${DIR}"
	else
		_listado_ "${H}"
	fi
}

_HORA_(){
	if [ -z $H ]
	then
		echo "INGRESA UN NUMERO DE HORAS hh"
		read -p "" H
	fi
}


_listado_(){
	H=$1
	source ${HOME}/.seiscomp.bash
	_HORA_
        date_begin=$(date -u --date="${H} hours ago" +"%Y-%m-%d %H:%M:%S")
        date_end=$(date -u +"%Y-%m-%d %H:%M:%S")
        scevtls -d mysql://${USR}:${PSWD}@${SERVIDOR}/${DB} \
		--begin "$date_begin" --end "$date_end"
}

_listado_quite_(){
	source ${HOME}/.seiscomp.bash
	H=$1
	DIR=$2
	_HORA_
        date_begin=$(date -u --date="${H} hours ago" +"%Y-%m-%d %H:%M:%S")
        date_end=$(date -u +"%Y-%m-%d %H:%M:%S")
        scevtls -d mysql://${USR}:${PSWD}@${SERVIDOR}/${DB} \
		--begin "$date_begin" --end "$date_end" > ${DIR}/sc_events.txt
#\
#		--quiet 1 > ${DIR}/sc_events.txt
}





while getopts :h:d:i:f:"q" option
do
	case "${option}"
	in
		h)
		export H=${OPTARG}
		;;

		d)
		export DIR=${OPTARG}
		;;

		q)
		export 	QUITE=1
		;;

		i)
		START_TIME=${OPTARG}
		export START_TIME
		;;

		f)
		END_TIME=${OPTARG}
		export END_TIME
		;;
	esac
done


_main_
