#!/bin/bash

export TEMP_FILE=/tmp/$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 5 | head -n 1).tmp
export CSV_FILE=/tmp/$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 5 | head -n 1).csv

_listado_(){
	FetchEvent --lat "12:18" --lon "-95:-88" -e $(date +%F,%T) -s $(date -d '5 days ago' +%F,%T) -o ${TEMP_FILE}
	sed -i 's/||//g' ${TEMP_FILE} #### aparecen ||| consecutivas
	echo -e "\n \n \n"

	if [[ ! -s ${TEMP_FILE} ]]
	then
		echo "no hay eventos"
		exit
		else
		while IFS="|" read ID OT_UTC LAT LON DEP info MAG REG more
		do
			OT_SEG=$(date -d "$OT_UTC" '+%s')
			echo "${OT_SEG} | ${ID} | ${LAT} | ${LON} | ${DEP} | ${info} | ${MAG} | ${REG} | ${more}" >> ${CSV_FILE}
		done < ${TEMP_FILE}
	fi

	sort -t '|' ${CSV_FILE} -o ${CSV_FILE}

	if [[ ! -s ${CSV_FILE} ]]
	then
		echo "no hay eventos"
		exit
		else
		while IFS="|" read OT_UTC ID LAT LON DEP info MAG REG more
		do
			echo "ID $ID"
			OT_LOCAL=$(TZ='America/Guatemala' date -d @"$OT_UTC" '+%F %T')
			echo "Origin time (LOCAL) $OT_LOCAL"
			echo "MAGNITUDE $MAG"
			echo "REGION $REG"
			echo -e "------- \n"
		done < ${CSV_FILE}
	fi
}

_listado_
rm ${CSV_FILE}
rm ${TEMP_FILE}
