#!/bin/bash
export PATH="/opt/seiscomp/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/VS/bin"
CONFIG="/home/insivumeh/Documents/insivumeh_sismo_group.conf"
FILE="/opt/VS/reportes/sismo/reporte_sismo.pdf"
CAPTION="BOLETIN --- EW"

if [ "$2" = "1" ]
then
	echo "$1" | sed 's/,/, ,/g'   | festival --tts
	echo "New event $3" &> /tmp/${3}.txt
	/usr/local/bin/telegram-send --config "$CONFIG"  --format html "<b>¡sismo registrado EW!</b> Early Warning id $3 , magnitud $5 ,Numero de estaciones $4"&>> /tmp/ew_${3}.txt
	/opt/VS/bin/sismo_ew -u "dacr" -s ${3} &>> /tmp/ew_${3}.txt && /usr/local/bin/telegram-send --config "$CONFIG" -f "$FILE" --caption "$CAPTION" &>> /tmp/ew_${3}.txt &
	/usr/local/bin/telegram-send --config "$CONFIG" -f "/tmp/${3}.txt" --caption "log sismo ew " &>> /tmp/ew_${3}.txt &
fi


