#!/bin/bash
export PATH="/opt/seiscomp/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/VS/bin"

CONFIG="/home/insivumeh/.telegram_send"
FILE="/opt/VS/reportes/sismo/reporte_sismo.pdf"
CAPTION="BOLETIN SISMOLÓGICO"


if [ "$2" = "1" ]
then
#	echo "$1" | sed 's/,/, ,/g'   | festival --tts
	echo "EEW has declare a new event $3" &> /tmp/${3}.log
	/usr/local/bin/telegram-send --config "$CONFIG"  --format html "<b>MENSAJE DE PRUEBA</b> EEW HA DECALARO UN SISMO id $3"&>> /tmp/${3}.log
fi

